### ISSUE TITLE
请教有关论文中的问题

### ISSUE THREAD

**Issue by zhuorson** [HKUDS/DSL#1]
作者好，刚拜读您的论文，对于文中有几个问题请教：
 1、下图中，交互的e没有转置，社交的e转置了，这是为什么？
![image](https://github.com/HKUDS/DSL/assets/32187278/2c66666d-47a9-4e1b-9af5-714e98b6c315)
2、公式（5）这个相似性投影函数，您是怎么得到的，设计思路是什么？

**Comment by louiswng** [comment]
你好，感谢你的关注：

1. 图中的转置操作为笔误，后续会进行更新。

2. 公式 (5) 的具体实现见 Model.py 中的 `label()` 函数。具体设计思路在公式 (5) 前一段有解释，主要是消除两个不同视图间的误差而进行变换对齐。

**Comment by zhuorson** [comment]
thank you for your patient
