### ISSUE TITLE
损失函数相关问题

### ISSUE THREAD

**Issue by Socialrec** [HKUDS/DSL#2]
![QQ截图20230808112231](https://github.com/HKUDS/DSL/assets/46867069/d185aaa0-35cf-4b3b-9b72-5c664d96ba10)
![image](https://github.com/HKUDS/DSL/assets/46867069/9afbc4eb-21c7-466b-bf2d-cf1b44cf6da4)
您好，在看你代码实现的时候Lrec的Ui和Lsoc的Ui不一样对吗

**Comment by louiswng** [comment]
抱歉回复不及时。是的，为方便实现，在函数 `sampSocialGraph` 中重新对 batch index 进行了采样。
