### ISSUE TITLE
关于测试集划分的问题

### ISSUE THREAD

**Issue by LiuZS10** [HKUDS/DSL#3]
作者您好，最近拜读了您的论文，有些疑问请您不吝赐教。
        请问作者在实验的过程中是怎样划分的训练集和测试集呢，以CiaoDVD数据集为例，test_Data.csv里有596000条，train.csv里矩阵值为1对应的是192221条数据，想了解下具体的数据划分方式。
        谢谢！

**Comment by jomainqaq** [comment]
看了一下代码，这篇论文测试的方法和LightGCN那种的单个用户u和所有物品算内积并全排列后，取top-k个物品计算Recall的方法不同。
具体可以看一下这篇论文 testEpoch 函数，里面直接对测试集里用户物品对求内积，然后 calcRes 函数计算HR和NDCG。
calcRes函数 `要求输入：preds: Inner product of user-item pairs.
            itm: Sampled items on interaction graph.`
我没看懂为什么这么做，但是听说NCF时期测试集里面不全是ground truth，没看过NCF代码不知道是不是这个原因，只是推测。
也希望作者能指正下

**Comment by LiuZS10** [comment]
@jomainqaq ，你好！最近研究了一下DSAL这个的测试过程，我是这样理解的，测试集里一个user对应了100个项目，第一个是有过交互的。LGCN计算跟所有item的内积然后算recall，dasl这个就只计算跟后面99个计算内积再计算recall了。这篇论文里4.2 Baseline Methods这个标题上面有这样一句话"We adopt a leave-one-out strategy, following similar settings as in [Long et al., 2021]." 同时引用了一篇文献，我的理解是这样的，不准确的话还请指正，不过之前确实没见过这样计算评价指标的

**Comment by jomainqaq** [comment]
@LiuZS10 你好！我比较好奇的是这篇文章把BatchSize和Dim也当作了超参进行选择，不知道是否对baseline的结果也进行了调参

**Comment by louiswng** [comment]
数据集的划分和计算评价指标都和之前的文章保持一致，详细可见引用论文 [Long et al., 2021] 的 4.1.2 Evaluation Protocols 部分。
- leave-one-out 是一种训练集和测试集的划分策略，表示随机选取 10% 的数据用来测试。
- 计算评价指标时，我们对目标用户采样了 99 个负样本。

baseline 也在一定范围内对 BatchSize 和 Dim 进行了调参。
