### ISSUE TITLE
数据集处理

### ISSUE THREAD

**Issue by merry-bat** [HKUDS/DSL#4]
作者您好！请问有处理数据集的代码吗？想要用别的数据集试试看，还有如何查看您的数据集内容啊，是乱码的

**Comment by louiswng** [comment]
你好，

1. 处理数据集的代码在 DataHandler.py 中。
2. 数据需要用 `pickle` 加载，加载数据的代码位于 DataHandler.py 中的 LoadData 函数。

**Comment by merry-bat** [comment]
> 你好，
> 
> 1. 处理数据集的代码在 DataHandler.py 中。
> 2. 数据需要用 `pickle` 加载，加载数据的代码位于 DataHandler.py 中的 LoadData 函数。
我想问一下原文的数据集数据是csv格式的，如何查看他的具体内容呀？还有就是一般的数据集如何处理得到原文的csv格式的数据，因为我想用FilmTrust数据集试试看。

**Comment by louiswng** [comment]
> > 你好，
> > 
> > 1. 处理数据集的代码在 DataHandler.py 中。
> > 2. 数据需要用 `pickle` 加载，加载数据的代码位于 DataHandler.py 中的 LoadData 函数。
> >    我想问一下原文的数据集数据是csv格式的，如何查看他的具体内容呀？还有就是一般的数据集如何处理得到原文的csv格式的数据，因为我想用FilmTrust数据集试试看。

你好，

因为命名的原因，这里可以把 .csv 当作是 .pkl 文件用 `pickle` 加载，然后 `print` 可以查看数据具体内容。
原始的数据集的处理脚本可以参考这篇工作的代码 [SMIN](https://github.com/SocialRecsys/SMIN/blob/main/dataset/Yelp/loadMat.py)，三个数据集的处理方式基本相同，在该仓库中都命名为 `loadMat.py`。

**Comment by zzzzljaa** [comment]
你好，看到你们的交流我收到了很大启发。
我同样想在FilmTrust数据集上跑一下这篇代码，但我跑出来的结果有点不太对。
请问你在FilmTrust数据集跑通了吗？盼回复。
