### ISSUE TITLE
请教关于自监督损失函数的问题

### ISSUE THREAD

**Issue by Socialrec** [HKUDS/DSL#5]
<img width="297" alt="image" src="https://github.com/HKUDS/DSL/assets/46867069/1d38f3fa-6132-4b3c-b397-81fae7a90114">
想请教您关于这个损失函数为什么可以去除噪声呢？

**Comment by louiswng** [comment]
这个公式为 hinge loss，优化时会拉近两个 z 之间的距离，也就是拉近两个用户间的交互相似度和社交相似度，从而消除社交视图的噪声。

**Comment by Socialrec** [comment]
如果两个用户之间交互相似度很低(即没有公共交互偏好)，要使得该损失函数减小，不应该对应社交相似度变高吗？这不是矛盾了吗？抱歉，我没有理解。

**Comment by Socialrec** [comment]
因为您加了sigmoid函数，因此用户之间相似度肯定是正数。

**Comment by louiswng** [comment]
在本文中，\hat z 与 z 是两个向量，他们的乘积表示这两个向量的相似度。要使得损失函数变小，则 \hat z 与 z 乘积对应增大，表示这两个向量的相似度变大，相当于拉近两个用户间的交互相似度和社交相似度。

**Comment by Socialrec** [comment]
但是您论文中和代码实现\hat z 与 z 都是一个数字🤔，如果是数字的话lable 是-1和1才能用hinge loss 吧。

**Comment by louiswng** [comment]
1. 不管用户间交互相似度的大小如何，要使得该损失函数减小，对应的社交相似度都会变高。但当某对用户间交互相似度低的时候，其社交相似度的优化梯度会较低；反之，社交相似度的优化梯度会较高。是通过这种方式来进行优化的。
2. 在函数图像上，BPR Loss 比 Hinge Loss 更加平滑。我们也尝试过 BPR Loss，但实验效果较差。

**Comment by Socialrec** [comment]
“不管用户间交互相似度的大小如何，要使得该损失函数减小，对应的社交相似度都会变高”，按照这个说法，当用户间没有相似的兴趣偏好时，交互相似度小，社交相似度高，这本身就是矛盾的啊？和优化梯度大小有什么关系呢？

**Comment by louiswng** [comment]
优化梯度可以从对变量求偏导理解。要使得该损失函数减小，当 z 很小时，\hat z 增大的程度小，优化梯度小；当 z 很大时，\hat z 增大的程度大，优化梯度大。
