### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by yyt1466028622** [HKUDS/DSL#7]
作者您好！我用CiaoDVD跑您代码的时候，发现这个数据集中train.pkl非零值数据的个数为192221，是不是说明user和item之间有交互的个数为192221？但是我看到CiaoDVD中test_Data.pkl中有596000条数据，这个数据比user和item之间交互个数还多，我想问下test_Data.pkl中的数据是什么数据呢？是怎么得来的呢？

**Comment by louiswng** [comment]
你好，感谢您的关注！

1. 在训练集中，user 和 item 之间的交互数为 192,221 次。
2. 在 test_Data.pkl 文件中，包含了 1:99 的正负样本比例，其中正样本（即 user 和 item 在测试集中的交互数）为 5,960 个。

如果您有任何问题，欢迎继续提问。
