### ISSUE TITLE
关于SMIN baseline结果的问题

### ISSUE THREAD

**Issue by fujiaxu0207** [HKUDS/DSL#8]
您好，文中SMIN的结果和Long et al., 2021的结果差距比较大，请问作者是自己重新跑了一篇baseline吗？谢谢！

**Comment by louiswng** [comment]
你好，

- Ciao和Epinions是自己处理的数据集，和SMIN中不同，所以是重新跑的；因为数据集处理的不同，不能直接进行数值比较。
- Yelp数据集比较大且处理复杂，所以直接使用了SMIN中提供的数据集，是汇报了SMIN论文中的结果。

如果还有疑问，欢迎继续提问。

**Comment by fujiaxu0207** [comment]
> 你好，
> 
> * Ciao和Epinions是自己处理的数据集，和SMIN中不同，所以是重新跑的；因为数据集处理的不同，不能直接进行数值比较。
> * Yelp数据集比较大且处理复杂，所以直接使用了SMIN中提供的数据集，是汇报了SMIN论文中的结果。
> 
> 如果还有疑问，欢迎继续提问。

好的，感谢您的回答！还有一个问题就是重新跑的代码使用的是SMIN论文本身提供的代码还是SSLRec 提供的代码呢（科研小白，不好意思）？

**Comment by louiswng** [comment]
1. 重新跑的代码是用SMIN论文提供的源代码。
2. SSLRec中SMIN的代码也是我们根据SMIN提供的源代码来复现的。

**Comment by fujiaxu0207** [comment]
> 1. 重新跑的代码是用SMIN论文提供的源代码。
> 2. SSLRec中SMIN的代码也是我们根据SMIN提供的源代码来复现的。

好的，感谢！

**Comment by fujiaxu0207** [comment]
> 你好，
> 
> * Ciao和Epinions是自己处理的数据集，和SMIN中不同，所以是重新跑的；因为数据集处理的不同，不能直接进行数值比较。
> * Yelp数据集比较大且处理复杂，所以直接使用了SMIN中提供的数据集，是汇报了SMIN论文中的结果。
> 
> 如果还有疑问，欢迎继续提问。

你好，请问这两个数据集是如何处理的呢？是否可以提供一下源码学习一下？十分感谢！

**Comment by louiswng** [comment]
> > 你好，
> > 
> > * Ciao和Epinions是自己处理的数据集，和SMIN中不同，所以是重新跑的；因为数据集处理的不同，不能直接进行数值比较。
> > * Yelp数据集比较大且处理复杂，所以直接使用了SMIN中提供的数据集，是汇报了SMIN论文中的结果。
> > 
> > 如果还有疑问，欢迎继续提问。
> 
> 你好，请问这两个数据集是如何处理的呢？是否可以提供一下源码学习一下？十分感谢！

你好，

原始数据集的处理脚本可以参考这篇工作的代码 [SMIN](https://github.com/SocialRecsys/SMIN/blob/main/dataset/Yelp/loadMat.py)，三个数据集的处理方式基本相同，在该仓库中都命名为 loadMat.py。

**Comment by fujiaxu0207** [comment]
> > > 你好，
> > > 
> > > * Ciao和Epinions是自己处理的数据集，和SMIN中不同，所以是重新跑的；因为数据集处理的不同，不能直接进行数值比较。
> > > * Yelp数据集比较大且处理复杂，所以直接使用了SMIN中提供的数据集，是汇报了SMIN论文中的结果。
> > > 
> > > 如果还有疑问，欢迎继续提问。
> > 
> > 
> > 你好，请问这两个数据集是如何处理的呢？是否可以提供一下源码学习一下？十分感谢！
> 
> 你好，
> 
> 原始数据集的处理脚本可以参考这篇工作的代码 [SMIN](https://github.com/SocialRecsys/SMIN/blob/main/dataset/Yelp/loadMat.py)，三个数据集的处理方式基本相同，在该仓库中都命名为 loadMat.py。

好的，谢谢
