### ISSUE TITLE
关于调参

### ISSUE THREAD

**Issue by LLLLMMMAS** [HKUDS/DSL#9]
您好，关于Ciao这个数据集跑出来的结果，HR=0.6374，NDCG=0.4065 。能否告知一下代码调参的数值是啥，我跑不出来这个结果

**Comment by louiswng** [comment]
您好，

- Ciao数据集上的参数已经放在了仓库中：https://github.com/HKUDS/DSL/blob/main/scripts/run_ciao.sh
- 尽管已经固定了seed，也会因为不同机器的硬件差异、库版本差异等原因导致结果不同。

感谢您的关注，欢迎提问。

**Comment by DualGraphsSR** [comment]
好的。谢谢
